"""The filter is the cost gate; every rule here maps to a line in sec. 4.1."""

from __future__ import annotations

import pytest

from app.domain.indexing.filtering import (
    DEFAULT_MAX_BYTES,
    Exclusion,
    FileFilter,
    FilterDecision,
)
from app.domain.indexing.models import Language


def evaluate(path: str, content: bytes, **kwargs: object) -> FilterDecision:
    return FileFilter(**kwargs).evaluate(path, len(content), content)  # type: ignore[arg-type]


class TestPathAndSize:
    @pytest.mark.parametrize(
        "path",
        [
            "node_modules/left-pad/index.js",
            "app/vendor/lib.py",
            "dist/bundle.ts",
            ".venv/lib/mod.py",
            "a/__pycache__/x.py",
            "build/out.js",
        ],
    )
    def test_vendored_paths_excluded(self, path: str) -> None:
        d = evaluate(path, b"x = 1\n")
        assert not d.included
        assert d.exclusion is Exclusion.VENDORED

    def test_unsupported_language_excluded(self) -> None:
        d = evaluate("README.md", b"# hi\n")
        assert d.exclusion is Exclusion.UNSUPPORTED_LANGUAGE

    def test_oversize_excluded_without_reading(self) -> None:
        f = FileFilter(max_bytes=10)
        assert not f.should_fetch("app/big.py", 11)
        assert f.should_fetch("app/small.py", 5)

    def test_gitignore_semantics(self) -> None:
        f = FileFilter.from_gitignore_text("secrets/\n*.secret.py\n")
        assert not f.should_fetch("secrets/key.py", 10)
        assert not f.should_fetch("app/db.secret.py", 10)
        assert f.should_fetch("app/main.py", 10)


class TestContentHeuristics:
    def test_binary_excluded(self) -> None:
        d = evaluate("app/mod.py", b"import os\x00\x01binary")
        assert d.exclusion is Exclusion.BINARY

    def test_minified_by_mean_line_length(self) -> None:
        d = evaluate("app/x.js", b"var a=1;" * 200)  # one very long line
        assert d.exclusion is Exclusion.MINIFIED

    def test_minified_by_name(self) -> None:
        d = evaluate("app/lib.min.js", b"short\n")
        assert d.exclusion is Exclusion.MINIFIED

    def test_generated_suffix_excluded(self) -> None:
        d = evaluate("app/schema_pb2.py", b"# stuff\n")
        assert d.exclusion is Exclusion.GENERATED
        assert d.is_generated

    def test_generated_header_excluded_by_default(self) -> None:
        d = evaluate("app/api.ts", b"// @generated by openapi\nexport const x = 1;\n")
        assert d.exclusion is Exclusion.GENERATED

    def test_generated_header_may_be_indexed_when_opted_in(self) -> None:
        d = evaluate(
            "app/api.ts",
            b"// @generated by openapi\nexport const x = 1;\n",
            index_generated=True,
        )
        assert d.included
        assert d.is_generated  # still flagged, just not dropped

    def test_hard_generated_suffix_ignored_even_when_opted_in(self) -> None:
        d = evaluate("app/x_pb2.py", b"# code\n", index_generated=True)
        assert d.exclusion is Exclusion.GENERATED


class TestClassification:
    def test_included_source_file(self) -> None:
        d = evaluate("app/main.py", b"def f():\n    return 1\n")
        assert d.included
        assert d.language is Language.PYTHON
        assert not d.is_test

    @pytest.mark.parametrize(
        "path",
        [
            "tests/test_x.py",
            "app/foo_test.py",
            "src/__tests__/x.ts",
            "src/x.test.ts",
            "src/x.spec.tsx",
        ],
    )
    def test_test_files_flagged(self, path: str) -> None:
        d = evaluate(path, b"x = 1\n")
        assert d.included
        assert d.is_test

    def test_default_max_bytes_is_one_megabyte(self) -> None:
        assert DEFAULT_MAX_BYTES == 1_000_000


class TestTwoPhase:
    def test_should_fetch_matches_evaluate_on_path_exclusions(self) -> None:
        f = FileFilter()
        # vendored: excluded in both phases, content never needed
        assert not f.should_fetch("node_modules/x.js", 3)
        # source file: phase one passes, content decides
        assert f.should_fetch("app/main.py", 3)
