"""Aggressive pre-parse filtering (ARCHITECTURE.md sec. 4.1).

> Filtering happens before parsing, and aggressively.

The cost model is the reason. Parsing and embedding are the expensive stages;
a minified bundle or a vendored ``node_modules`` tree that slips through inflates
cost and pollutes retrieval with noise. So the filter is two-phase:

* :meth:`FileFilter.should_fetch` decides from *path and size alone* -- cheap
  facts available from ``git ls-tree`` -- so an excluded blob is never even
  downloaded from the bare clone.
* :meth:`FileFilter.evaluate` runs the content-dependent checks (binary sniff,
  minification, generated-header detection) on blobs that survived phase one.

The decision logic here is pure; the walking/statting/reading that feeds it is
infra. That split is what makes every rule below a table-driven unit test.
"""

from __future__ import annotations

from dataclasses import dataclass
from enum import StrEnum
from typing import Any

import pathspec

from app.domain.indexing.models import Language

__all__ = ["Exclusion", "FileFilter", "FilterDecision"]

# 1 MB. A source file larger than this is generated, vendored, or data.
DEFAULT_MAX_BYTES = 1_000_000

# Mean line length above which a text file is treated as minified. A hand-written
# source file averages well under 100; a minified bundle is one 40 kB line.
DEFAULT_MINIFIED_MEAN_LINE_LENGTH = 200

# Path segments that mark a vendored or build-output tree. Matched against every
# component of the path, so ``a/node_modules/b`` and ``node_modules/b`` both hit.
_VENDORED_SEGMENTS: frozenset[str] = frozenset(
    {
        "node_modules", "bower_components", "jspm_packages", "vendor",
        "third_party", "site-packages", "dist", "build", "out", "target",
        ".venv", "venv", ".tox", ".nox", ".git", "__pycache__", ".mypy_cache",
        ".pytest_cache", ".ruff_cache", ".cache", ".next", ".nuxt",
        ".svelte-kit", "coverage", "htmlcov", ".gradle", ".idea",
    }
)

# Filename suffixes that are generated by construction; excluded outright.
_GENERATED_SUFFIXES: tuple[str, ...] = (
    "_pb2.py", "_pb2_grpc.py", ".pb.ts", ".pb.js",
    ".gen.ts", ".gen.js", ".generated.ts", ".generated.js", ".d.ts",
)

# Substrings that mark minified assets regardless of measured line length.
_MINIFIED_SUFFIXES: tuple[str, ...] = (".min.js", ".min.css", ".min.mjs")

# Header markers (checked in the first few KB) that flag machine-written files
# which may still be hand-edited -- soft signal, so the file is *flagged*
# generated rather than dropped, unless a hard suffix above already excluded it.
_GENERATED_MARKERS: tuple[bytes, ...] = (
    b"@generated", b"DO NOT EDIT", b"DO NOT MODIFY",
    b"Code generated by", b"AUTO-GENERATED", b"autogenerated by",
)

_TEST_DIR_SEGMENTS: frozenset[str] = frozenset({"tests", "test", "__tests__"})
_HEADER_SNIFF_BYTES = 4096


class Exclusion(StrEnum):
    """Why a file was excluded. ``NONE`` means it was kept.

    Surfaced (not just a bool) because the index-lag and coverage metrics want to
    attribute exclusions -- "we dropped 4k files, 3.9k vendored" is debuggable;
    "we dropped 4k files" is not.
    """

    NONE = "none"
    UNSUPPORTED_LANGUAGE = "unsupported_language"
    TOO_LARGE = "too_large"
    VENDORED = "vendored"
    GITIGNORED = "gitignored"
    BINARY = "binary"
    MINIFIED = "minified"
    GENERATED = "generated"


@dataclass(frozen=True, slots=True)
class FilterDecision:
    included: bool
    exclusion: Exclusion
    language: Language | None
    is_test: bool
    is_generated: bool


class FileFilter:
    """Decides which files enter the index. Stateless apart from its config and
    an optional compiled ``.gitignore`` matcher."""

    def __init__(
        self,
        *,
        gitignore: pathspec.PathSpec[Any] | None = None,
        max_bytes: int = DEFAULT_MAX_BYTES,
        minified_mean_line_length: int = DEFAULT_MINIFIED_MEAN_LINE_LENGTH,
        index_generated: bool = False,
    ) -> None:
        self._gitignore: pathspec.PathSpec[Any] | None = gitignore
        self._max_bytes = max_bytes
        self._minified_mean_line_length = minified_mean_line_length
        self._index_generated = index_generated

    @classmethod
    def from_gitignore_text(cls, text: str, **kwargs: object) -> FileFilter:
        """Compile a ``.gitignore`` blob into a matcher. Convenience for the
        source walker, which reads the repo's root ``.gitignore`` at head."""
        spec = pathspec.PathSpec.from_lines("gitignore", text.splitlines())
        return cls(gitignore=spec, **kwargs)  # type: ignore[arg-type]

    # -- phase one: path + size only ------------------------------------- #

    def _path_exclusion(self, path: str, size_bytes: int) -> Exclusion:
        if Language.for_path(path) is None:
            return Exclusion.UNSUPPORTED_LANGUAGE
        segments = path.split("/")
        if any(seg in _VENDORED_SEGMENTS for seg in segments):
            return Exclusion.VENDORED
        if self._gitignore is not None and self._gitignore.match_file(path):
            return Exclusion.GITIGNORED
        if size_bytes > self._max_bytes:
            return Exclusion.TOO_LARGE
        return Exclusion.NONE

    def should_fetch(self, path: str, size_bytes: int) -> bool:
        """True if the blob is worth downloading and content-checking. Excludes,
        on path and size alone, everything cheaply excludable."""
        return self._path_exclusion(path, size_bytes) is Exclusion.NONE

    # -- phase two: with content ----------------------------------------- #

    def evaluate(self, path: str, size_bytes: int, content: bytes) -> FilterDecision:
        """Full decision for a fetched blob."""
        language = Language.for_path(path)
        path_exclusion = self._path_exclusion(path, size_bytes)
        if path_exclusion is not Exclusion.NONE:
            return FilterDecision(False, path_exclusion, language, False, False)

        if b"\x00" in content[:_HEADER_SNIFF_BYTES]:
            return FilterDecision(False, Exclusion.BINARY, language, False, False)

        if self._is_minified(path, content):
            return FilterDecision(False, Exclusion.MINIFIED, language, False, False)

        is_generated = self._is_generated(path, content)
        hard_generated = path.endswith(_GENERATED_SUFFIXES)
        if is_generated and (hard_generated or not self._index_generated):
            return FilterDecision(False, Exclusion.GENERATED, language, False, True)

        return FilterDecision(
            included=True,
            exclusion=Exclusion.NONE,
            language=language,
            is_test=self._is_test(path),
            is_generated=is_generated,
        )

    # -- content heuristics ---------------------------------------------- #

    def _is_minified(self, path: str, content: bytes) -> bool:
        if path.endswith(_MINIFIED_SUFFIXES):
            return True
        if not content:
            return False
        newlines = content.count(b"\n") + 1
        return len(content) / newlines > self._minified_mean_line_length

    @staticmethod
    def _is_generated(path: str, content: bytes) -> bool:
        if path.endswith(_GENERATED_SUFFIXES):
            return True
        head = content[:_HEADER_SNIFF_BYTES]
        return any(marker in head for marker in _GENERATED_MARKERS)

    @staticmethod
    def _is_test(path: str) -> bool:
        segments = path.split("/")
        if any(seg in _TEST_DIR_SEGMENTS for seg in segments[:-1]):
            return True
        name = segments[-1]
        stem = name.rsplit(".", 1)[0]
        return (
            stem.startswith("test_")
            or stem.endswith("_test")
            or ".test" in name
            or ".spec" in name
        )
